<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.2.3"/>
		<PackageReference Include="Avalonia.Desktop" Version="11.2.3"/>
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3"/>
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3"/>

		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.2.3">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>

		<PackageReference Include="CommunityToolkit.Labs.Extensions.DependencyInjection" Version="0.1.250103-build.1988"/>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0"/>

		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Athan.Services\Athan.Services.csproj"/>
	</ItemGroup>
</Project>