//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athan.Avalonia.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Athan.Avalonia.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ApplicationLanguage {
            get {
                return ResourceManager.GetString("ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        public static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        public static string Asr {
            get {
                return ResourceManager.GetString("Asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        public static string Dhuhr {
            get {
                return ResourceManager.GetString("Dhuhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajr.
        /// </summary>
        public static string Fajr {
            get {
                return ResourceManager.GetString("Fajr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographical Location.
        /// </summary>
        public static string GeographicalLocation {
            get {
                return ResourceManager.GetString("GeographicalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang tight....
        /// </summary>
        public static string HangTight {
            get {
                return ResourceManager.GetString("HangTight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection is required for Athan to function as expected. You may proceed when internet connectivity is established.
        /// </summary>
        public static string InternetConnectivityRequired {
            get {
                return ResourceManager.GetString("InternetConnectivityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Isha {
            get {
                return ResourceManager.GetString("Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        public static string Maghrib {
            get {
                return ResourceManager.GetString("Maghrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Prayer.
        /// </summary>
        public static string NextPrayer {
            get {
                return ResourceManager.GetString("NextPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no!.
        /// </summary>
        public static string OhNo {
            get {
                return ResourceManager.GetString("OhNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocate.
        /// </summary>
        public static string Relocate {
            get {
                return ResourceManager.GetString("Relocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while processing the request.
        /// </summary>
        public static string RequestErrorOccured {
            get {
                return ResourceManager.GetString("RequestErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart is required for some changes to take effect.
        /// </summary>
        public static string RestartRecommended {
            get {
                return ResourceManager.GetString("RestartRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you.
        /// </summary>
        public static string WhereAreYou {
            get {
                return ResourceManager.GetString("WhereAreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the prayer time for.
        /// </summary>
        public static string YouHaveEnteredThePrayerTimeFor {
            get {
                return ResourceManager.GetString("YouHaveEnteredThePrayerTimeFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to be in.
        /// </summary>
        public static string YouSeemToBeIn {
            get {
                return ResourceManager.GetString("YouSeemToBeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to be offline.
        /// </summary>
        public static string YouSeemToBeOffline {
            get {
                return ResourceManager.GetString("YouSeemToBeOffline", resourceCulture);
            }
        }
    }
}
